### ISSUE TITLE
Need Korean name for Litecoin

### ISSUE THREAD

**Issue by wtogami** [litecoin-project/litecoin#190]
"비트코인 코어" is Bitcoin Core.  We need a similar name for Litecoin.

**Comment by thrasher-** [comment]
"라이트 코인 코어" is Litecoin Core

**Comment by wtogami** [comment]
Are people already using that name?  Most languages stick with the English name because it is more recognizable.

**Comment by losh11** [comment]
I was also wondering about this, because I was not so sure on how to translate parts of the litecoin.com site.

Usually I see big companies using the trademarked name (in english) to show products when translated. So the iPhone is always written out as 'iPhone', no matter what language the device has been localized to.

**Comment by thrasher-** [comment]
Doing a search on Google yields many results using the Korean translation of Litecoin, https://www.google.com/search?q=라이트+코인&oq=라이트+코인

The bitcoin.org site also uses the translated version of Bitcoin too. Perhaps we should do the same?

**Comment by losh11** [comment]
Not too sure about Korean, but some languages don't have the exact sounds as English. This can make some work sound really weird when writing it in another language, sometimes making it not sound like Litecoin at all.

**Comment by wtogami** [comment]
The Google search seems a good enough reason to use that name.
