### ISSUE TITLE
Max Block Size?

### ISSUE THREAD

**Issue by losh11** [litecoin-project/litecoin#194]
Will we be increasing the max block size? If so to what size, because I personally think that 20 MB is too big...
So something like this:- https://github.com/gavinandresen/bitcoin-git/commit/5f46da29fd02fd2a8a787286fd6a56f680073770

Sorry meant something else.

**Comment by wtogami** [comment]
Our magic number is NOT the same as bitcoin.  Where did you get that idea?

Changing Bitcoin's block size is subject to a major political battle.  It introduces a number of serious risks without solving the underlying problems.  Side-chains are a better solution to tackle the scalability problem.

In the case of Litecoin we have no scalability problem anytime soon (for years) because our anti-spam rules better ensures that the vast majority of our transaction outputs are economically viable in relation to the fee of spending outputs.  That combined with the 4x more often blocks allows us considerably more room to evaluate and adopt better technical solutions.

**Comment by losh11** [comment]
Can we have some solid facts on how many tps we have, and some other info - some of it isn't generally known and is sometimes speculation.

I believe we have 7*4 -> 28transactions per second. Any other additional info to make it easier for people to make a decision on the important thing?

**Comment by wtogami** [comment]
7*4 is only the baseline.  Beyond that is the very real benefit Litecoin has long had with its anti-spam mechanism making transactions that do happen to not be crowded out by worthless spam outputs.

Increasing block size is a very inefficient way of improving the TPS of a network.  It may seem obvious and easy, but it can make other problems far worse like centralization and exacerbate the orphan advantage that the largest mining pools have over others.  It is far more efficient to use more technically sophisticated means of allowing greater scaling like low trust micro-payment channels and side-chains.  This is a serious debate happening now for the Bitcoin community as growing the maximum block size alone does not actually solve any of the underlying problems.

**Comment by pcdinh** [comment]
>> Increasing block size is a very inefficient way of improving the TPS of a network.
You mean block size limit? Increasing block size limit does not increase effective block size which is practically decided by miners. If Litecoin network gets a lot of transactions, increasing block chain is unavoidable or confirmation speed is unpredictable, which reduces trust in the network. Working with a payment network is the same like working with a business. If it is unreliable, unpredictable, its users will be out. Bitcoin has no monopoly power. Its network effect can reduce over time

side-chains are vaporware at the moment. Also, side-chains are just altcoin blockchain that has fixed exchange rate with bitcoin. People want to use bitcoin on Bitcoin network, not sidechain-enabled altcoin. http://en.wikipedia.org/wiki/Nirvana_fallacy

Fortunately, Litecoin has a lot of times to see if such innovations can become reality
