### ISSUE TITLE
Error initializing wallet database environment

### ISSUE THREAD

**Issue by JoinJoin** [litecoin-project/litecoin#209]
After compiling the latest version, Litecoin Core version v0.10.2.2-228abe4 (64-bit), litecoin-qt refuses to start and gives me:
"Error initializing wallet database environment" 

I cleaned up my ./litecoin directory but I still get the error

debug.log

```
2015-07-06 07:44:02 Litecoin version v0.10.2.2-228abe4 (2015-06-21 10:29:13 +1000)
2015-07-06 07:44:02 Using OpenSSL version OpenSSL 1.0.1f 6 Jan 2014
2015-07-06 07:44:02 Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2015-07-06 07:44:02 Default data directory /home/blahhh/.litecoin
2015-07-06 07:44:02 Using data directory /home/blahhh/.litecoin
2015-07-06 07:44:02 Using config file /home/blahhh/.litecoin/litecoin.conf
2015-07-06 07:44:02 Using at most 125 connections (1024 file descriptors available)
2015-07-06 07:44:02 Using 2 threads for script verification
2015-07-06 07:44:02 Using wallet wallet.dat
2015-07-06 07:44:02 init message: Verifying wallet...
2015-07-06 07:44:02 CDBEnv::Open : LogDir=/home/blahhh/.litecoin/database ErrorFile=/home/blahhh/.litecoin/db.log
2015-07-06 07:44:02 ERROR: CDBEnv::Open : Error 22 opening database environment: Invalid argument

2015-07-06 07:44:02 Moved old /home/blahhh/.litecoin/database to /home/blahhh/.litecoin/database.1436168642.bak. Retrying.
2015-07-06 07:44:02 CDBEnv::Open : LogDir=/home/blahhh/.litecoin/database ErrorFile=/home/blahhh/.litecoin/db.log
2015-07-06 07:44:02 ERROR: CDBEnv::Open : Error 22 opening database environment: Invalid argument

2015-07-06 07:44:04 Shutdown: In progress...
2015-07-06 07:44:04 StopNode()
2015-07-06 07:44:04 Shutdown: done
```

**Comment by thrasher-** [comment]
Was this a fresh installation or an upgrade of an existing Litecoin installation? This trends to happen if you used a BDB version originally differing from 4.8.30, then switched to a version which uses it - causing wallet compatibility issues.

Before doing any steps, make sure you have your wallet.dat file backed up. Then try the following:

a) Recompiling Litecoin with the same version BDB version you used originally.
b) Running the old Litecoin binary, dumping the priv keys of the addresses, trashing the old wallet database then running Litecoin with the recommended BDB version (4.8.30) to create a new wallet database. Then import the keys into the new wallet.

**Comment by JoinJoin** [comment]
Installing  BDB 4.8.30 and keeping it installed is a real PITA in Kubuntu and I stopped using this more than a year ago. 

I had previous version (0.8.7.5) of litecoind and litecoin-qt running with same BDB as this one. 
I even used --with-incompatible-bdb or it wont compile.

**Comment by thrasher-** [comment]
With your previous statement in issue #206:

'I have libdb4.8++ and libdb5.3++-dev installed and I have used > 5. forever with my litecoin-qt and litecoind', 

The reason why your getting the above error is because your original database was generated using a higher version of BDB and your current build has been linked with 4.8.30 thus leading to wallet compatibility issues. 

```2015-07-06 07:44:02 Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)```

Having to specify --with-incompatible-bdb or it wont compile is expected because autoconf is detecting a different version installed then 4.8.30. Your configure log shows this

```configure: WARNING: Found Berkeley DB other than 4.8; wallets opened by this build will not be portable!```

To resolve the issue, you have the following issues:

a) Remove BDB 4.8.30 entirely, recompile Litecoin Core using the bdb version you've always used (which going off your comment is libdb5.3) with the --with-incompatible-bdb flag.
b) If you do not wish to preserve your wallet if it contains no Litecoins but want to use your current build, you could rename your wallet.dat file and database folder. Then relaunch Litecoin for it to rebuild them.
c) If your wallet contains addresses with balances but you wish to use the compatible BDB version, you could dump the private keys for those addresses using the old Litecoin version, rename your wallet.dat file and database folder. Launch Litecoin 0.10.2.2 to build a new wallet and database. Then import the private keys.

NOTE: We always release binaries with 4.8.30 support to prevent wallet compatibility issues between versions.

**Comment by JoinJoin** [comment]
Thank you for your quick, well written and clear answers. 
I am going to start with a) and see, what happens. I can not lose my wallets, so b) is out. 
I have a old version of litecoind available so if nothing else works, I'll use c)

**Comment by thrasher-** [comment]
No problem, please let us know how you go!

**Comment by JoinJoin** [comment]
This is turning in to a real cluster fuck. 

OK, now I know why I have 4.8.30 installed. It's because of bitcoin and I can not nuke it because I have coins in my BTC wallet. 

Question is, how can I force litecoin-qt and litecoind to be built with libdb5.3, also used by my PPC wallet.

**Comment by thrasher-** [comment]
You could try something like this:

./configure CPPFLAGS="-I/usr/local/BerkeleyDB.5.3/include -O2" LDFLAGS="-L/usr/local/BerkeleyDB.5.3/lib" --with-incompatible-bdb

You'll need to substitute the paths to your actual lib and include folders.

**Comment by JoinJoin** [comment]
Kubuntu has nothing like it in /usr/local... 
What files are there? 
I'll search for them and then change the path accordingly

**Comment by JoinJoin** [comment]
File list of package libdb5.3-dev in trusty of architecture amd64

/usr/include/db.h
/usr/include/db_185.h
/usr/lib/x86_64-linux-gnu/libdb-5.3.a
/usr/lib/x86_64-linux-gnu/libdb.a
/usr/lib/x86_64-linux-gnu/libdb.so
/usr/share/doc/libdb5.3-dev


File list of package libdb5.3++ in trusty of architecture amd64

/usr/lib/x86_64-linux-gnu/libdb_cxx-5.3.so
/usr/share/doc/libdb5.3++
/usr/share/lintian/overrides/libdb5.3++

**Comment by thrasher-** [comment]
Can you confirm where the 4.8 files are installed to? If its in a custom directory, great but if it has been installed into the default directories, then that is going to be problematic.

In relation to the db 4.8.30 log statement and --with-incompatible-version warning. There is a chance that it did actually use 5.3 even though the log mentioned 4.8.30. So, as an easy test without having to mess around with your operating system, please download the latest Litecoin Core version from https://litecoin.org/ and see if you still get the same message when running it.

**Comment by JoinJoin** [comment]
thrasher, I downloaded the binary version as you recommended and I get no errors. 
Now I am even more confused :) <-- rally stupid clueless grin, with a side order of drool

**Comment by thrasher-** [comment]
Excellent! That confirms that your prior versions were actually compiled with BDB 4.8.30, same with your Bitcoin client which is why you can open your wallet file using the downloaded binary version as it uses 4.8.30.

When you attempted to compile Litecoin, it was actually using BDB 5.3 despite the log file saying 4.8.30 thus leading to an error.

So, if you're happy using the non compiled version, that will solve the issue. However, if you wish to compile it from source, then I'd recommend removing 5.3 and just leaving 4.8.30 installed for all future versions until this dependency changes.

**Comment by JoinJoin** [comment]
Thank you for your time. Closing this.
