### ISSUE TITLE
security: too old OpenSSL version included in offered litecoin binary

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [litecoin-project/litecoin#231]
The prebuilt litecoin QT version (1) uses a 1-year old OpenSSL version (2).

There were 6 releases afterwards (3) with many security fixes (4).

Please upgrade to openssl-1.0.1q from Dec 2015
Thank you!

(1) I checked only so far: 
https://download.litecoin.org/litecoin-0.10.4.0/linux/litecoin-0.10.4.0-linux32.tar.gz
 
(2) 1.0.1k from 8th Jan 2015
(3) http://www.openssl.org/source/old/1.0.1/
(4) http://www.openssl.org/news/newslog.html

**Comment by losh11** [comment]
I assume that OpenSSL 1.0.2e is the latest build. Even Bitcoin Core hasn't updated.

Will submit a PR.

**Comment by thrasher-** [comment]
We don't update OpenSSL to newer versions unless there's a critical vulnerability patched which impacts Litecoin (or Bitcoin) and also due to the risk of upstream changes potentially causing consensus compatibility issues which can't be picked up easily in tests (like the architecture inconsistency issue fixed in BIP66).

Litecoin and Bitcoin only use specific features of OpenSSL and the security changes addressed aren't significant enough to update it yet. 

With 0.10.4 and our next 0.12 release we are reducing the need for OpenSSL.

With that said, you still can compile Litecoin with a newer version of OpenSSL but for the official release binaries we will stick with a well known and tested version.
