### ISSUE TITLE
How do i build windows qt?

### ISSUE THREAD

**Issue by njbrown09** [litecoin-project/litecoin#310]
I followed the instructions in build-windows. It just crashes on startup

**Comment by losh11** [comment]
Please post a copy of your debug.log file. It can be found in the [Litecoin Data Directory](https://litecoin.info/Data_directory).

**Comment by njbrown09** [comment]
it dosent even get to the point where it creats a debug log. I tried debugging it with visual studio and it says its getting an access violation

**Comment by losh11** [comment]
What branch did you build from? Master (0.13.3) or 0.14-dev?

**Comment by njbrown09** [comment]
Directly off the github master branch

**Comment by njbrown09** [comment]
im going to assume that it is 0.13.3 (I just did git clone)

**Comment by FaysalM** [comment]
If you are using windows 10, try compiling with the windows linux sub-system. The mingw support for both bitcoin (and by extension LTC) is not good, and you will always run into issues. Alternatively you could compile in linux and port (which should work fine). Use something like Virtualbox for a VM on windows if needed. Also you will not be able to compile or debug in Visual Studio, unless you port the whole project over. Since the UI is all QT, I am pretty sure VS will not support that. Alternatively you could build the native libraries as DLLs and build you own GUI.

Here are some steps to build bitcoin, you should be able follow them exactly for litecoin.
https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md

**Comment by thrasher-** [comment]
Closed due to inactivity.

**Comment by vanshtah** [comment]
> If you are using windows 10, try compiling with the windows linux sub-system. The mingw support for both bitcoin (and by extension LTC) is not good, and you will always run into issues. Alternatively you could compile in linux and port (which should work fine). Use something like Virtualbox for a VM on windows if needed. Also you will not be able to compile or debug in Visual Studio, unless you port the whole project over. Since the UI is all QT, I am pretty sure VS will not support that. Alternatively you could build the native libraries as DLLs and build you own GUI.
> 
> Here are some steps to build bitcoin, you should be able follow them exactly for litecoin.
> https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md

I have followed all the steps but it is not working
