### ISSUE TITLE
I have a problem in solo mining

### ISSUE THREAD

**Issue by Alexitnovoros** [litecoin-project/litecoin#360]
Good day!
I have a problem with solo mining on localhost. Please help me.
When I start cgminer or sgminer on localhost it dont connect to litecoin wallet and write string:
Pool 0 slow/down or URL or credentials invalid

litecoin.conf:

```

rpcuser=uuu
rpcpassword=pass
rpcallowip=127.0.0.1
rpcport=9332
daemon=1
server=1
gen=0

block_nTime=1317972665
block_nNonce=2084524493
```

cgminer 3.7.2 start.bat :

```
setx GPU_USE_SYNC_OBJECTS 1
cgminer --scrypt -o localhost:9332 -u uuu -p pass 
pause
```

I use OS windows 7 64

**Comment by thrasher-** [comment]
CGMiner doesn't support GBT solo mining in that release from memory. Are you solo mining testnet or mainnet? For testnet, please download and setup cpuminer. You can see the launch parameters here: https://github.com/litecoin-project/litecoin/issues/355. If for mainnet, solo mining isn't feasible now without a large ASIC farm.

**Comment by Alexitnovoros** [comment]
I use mainnet. When I use CGMiner 3.0.1 he say "Pool 0 slow/down or URL or credentials invalid" too.

**Comment by thrasher-** [comment]
Are you ASIC or GPU mining? Later versions support GBT but don't support GPU's. Older versions support GPU's but don't support GBT.

**Comment by Alexitnovoros** [comment]
I use GPU mining. What is GBT?

**Comment by thrasher-** [comment]
BFGMiner 5.4 doesn't enable GPU support by default. The readme states 'OpenCL GPUs, such as AMD Radeons (disabled by default, see README.GPU)' So you'll need to follow those instructions for it to work. Again, please also note that GPU mining is obsolete and won't be worth your time as it is not feasible to generate a block solo mining.

**Comment by mraksoll** [comment]
i think dev is idiot end they do not understand about JSON not work , it's not accept connection from miner, no mater for solo mining or not it's not accept connection's. But they is last idiot end say GPU miner is not profitable facepalm.

**Comment by thrasher-** [comment]
@mraksoll I see that you have edited your post to remove the name calling to make it nicer, however If you can't understand that the readme of the software states that the particular version doesn't support GPU mining by default and that additional steps must be taken, then please keep quiet. Solo mining requires a getblocktemplate compatible mining client (old mining software using getwork won't work and will throw JSON handling errors) which talks to the Litecoin RESTful API.  That BFGMiner version can do it, but requires additional steps as my response clearly stated. Including:

Compiling with `./configure --enable-scrypt` will support generic GPU drivers, for more specific instructions you can follow:
https://github.com/luke-jr/bfgminer/blob/bfgminer/README.scrypt

After compilation, the very basic launch params should look something like:
`./bfgminer --scrypt -o http://localhost:9332 -u uuu -p pass --generate-to <address>`

An out of the box easy solution I use to solo mine testnet is https://github.com/pooler/cpuminer with the launch parameters linked above.

As for GPU mining being profitable:
https://www.cryptocompare.com/mining/calculator/ltc?HashingPower=980&HashingUnit=KH%2Fs&PowerConsumption=300&CostPerkWh=0.12 

Stats for a Radeon 290, you will lose -94% per day or -$294 per yr (and this is pool mining, you won't generate a reward from GPU solo mining until you solve a block which is virtually impossible now). Obviously there is newer generation cards which might double performance, but you'd still lose money due to the severe advantage ASIC miners have over GPU's.

Closing this issue as this is outside the scope of Litecoin Core issues and more to do with mining software. Please feel free to discuss this at  https://litecointalk.io however.

**Comment by mraksoll** [comment]
ok what do with pool what use this RPC call's ?

**Comment by losh11** [comment]
Again as recommended, please discuss this on litecointalk.org. The Litecoin Core project is no such place to ask these questions.

**Comment by mraksoll** [comment]
Or if people try create altcoin, end solo mine, the RPC not work end you are idiot , i to want know whay absolutely not work daemon ?

**Comment by mraksoll** [comment]
but other coin even bitcoin it's absolutely normally on latest sources.

**Comment by mraksoll** [comment]
what you are say about cpuminer 

[2017-07-25 03:51:55] Binding thread 0 to cpu 0
[2017-07-25 03:51:55] Binding thread 1 to cpu 1
[2017-07-25 03:51:55] Binding thread 2 to cpu 2
[2017-07-25 03:51:55] 4 miner threads started, using 'scrypt' algorithm.
[2017-07-25 03:51:55] Binding thread 3 to cpu 3
[2017-07-25 03:51:55] HTTP request failed: The requested URL returned error: 500
 Internal Server Error
[2017-07-25 03:51:55] json_rpc_call failed, retry after 30 seconds

?????
