### ISSUE TITLE
Fee estimation is wrong/too high better to disable

### ISSUE THREAD

**Issue by montvid** [litecoin-project/litecoin#402]
### Describe the issue
Fee estimation is wrong/too high in litecoin core - now 0.00200810ltc/kb but the blocks are never full so 0.001ltc/kb works to get into the next block. Please fix the algorithm or set the tick to use 0.001ltc/kb in the gui by default as there is no need for fee estimation because the blocks are never full. It may be a problem for the algorithm that I am not running my core client 24/7 only when I make transactions. The node is fully synced. 
### Can you reliably reproduce the issue?
Yes
### Expected behaviour
Fee 0.001ltc/kb

### Actual behaviour
Fee is usually >0.001
Fee >0.002ltc/kb

### Screenshots.
![pic](https://user-images.githubusercontent.com/23270059/33781407-2c3e479e-dc5d-11e7-9fc8-5838b8b35099.png)

### What version of litecoin-core are you using?
14.2 downloaded from https://litecoin.org/

**Comment by montvid** [comment]
And what about the insane fees shown in https://live.blockcypher.com/ltc/ and https://chain.so/ltc ???

**Comment by edinjusupovic** [comment]
It appears the estimated fees are high on those blockchain sites because their nodes are running with the standard maximum memory pool of 5MB.

**Comment by montvid** [comment]
@edinjusupovic okay, but it still means that someone is paying these high fees, maybe using other clients, no? I read that bitcoin 15 had made some adjustments in fee estimation, maybe when litecoin integrates  btc 15 the algorithm will be better.

**Comment by thrasher-** [comment]
The inflated fees came about and are fixed by:

- Congestion on the Litecoin network at the time.
- 5MB mempool limit. For a long time Litecoin didn't have much transaction per block volume so we lowered the limit to this. During the excitement over the past few months the mempool limit was hit, which lead to the mempool getting crowded and drives up the mempoolminfee, which evicts low fee transactions. We've now set the limit to 300MB. This gives transactions with lower fees less chance of getting evicted. You can also adjust this value manually by setting -maxmempool=<n> where n is the size in MB.
- 0.15.1 contains fee code improvements, as well as lowering the minrelayfee.
- You can adjust the recommended transaction fee to a lower value (default is a block confirmation target of 2).
- You can set a custom fee to the network minimum (0.001 LTC).
- Currently I've got a reading of 0.00100282 LTC/kB.

Closing issue.
