### ISSUE TITLE
Are signed message signatures generated from a '3' and corresponding 'M' address the same?

### ISSUE THREAD

**Issue by EvilJordan** [litecoin-project/litecoin#439]
I've got a publicAddress of:  `MB5PRHzpfw1GAUa53Lk3wycDTb7rLqM9Rc`
This can be translated to: `34sF7Qarip9qMyJAwTki8LMp8tXQMyUitM`

(I used [this](https://litecoin-project.github.io/p2sh-convert/) tool)

I'm using a TREZOR, and it will only let me sign a message with the 'M' address.

Does anyone know if I were able to sign a message with the '3' address, would 1) the signature be the same [I expect not] and 2) would the same verification algorithm work on the '3' address that verifies the 'M' address?

**Comment by losh11** [comment]
The signature should be the same.

**Comment by thrasher-** [comment]
Trezor only supports P2PKH (legacy addresses, since a public key can only correspond to one P2PKH address) and P2SH-P2WPKH(p2sh-segwit) for message signing/verification using an extended header which is non standard. This is why M addresses work but addresses with 3 does not (as that would be considered a P2SH address and it is not possible to do signing/verification on P2SH addresses). Note that Litecoin Core only supports signmessage/verifymessage for P2PKH addresses. Once the standard is decided, then it will be rolled out for bech32 and P2SH-segwit addresses.
