### ISSUE TITLE
make check error

### ISSUE THREAD

**Issue by vasikokk** [litecoin-project/litecoin#555]
Ubuntu 16.04 LTS

root@mcvk:~/litecoin# make check
Making check in src
make[1]: Entering directory '/root/litecoin/src'
make[2]: Entering directory '/root/litecoin/src'
make  check-TESTS check-local
make[3]: Entering directory '/root/litecoin/src'
make[4]: Entering directory '/root/litecoin/src'
FAIL: test/test_litecoin
============================================================================
Testsuite summary for Litecoin Core 0.16.3
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
Please report to https://github.com/litecoin-project/litecoin/issues
============================================================================
Makefile:9651: recipe for target 'test-suite.log' failed
make[4]: *** [test-suite.log] Error 1
make[4]: Leaving directory '/root/litecoin/src'
Makefile:9757: recipe for target 'check-TESTS' failed
make[3]: *** [check-TESTS] Error 2
make[3]: Leaving directory '/root/litecoin/src'
Makefile:9863: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/root/litecoin/src'
Makefile:9544: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/root/litecoin/src'
Makefile:748: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

**Comment by thrasher-** [comment]
Could you please copy the contents of `src/test-suite.log` and paste them here.

**Comment by thrasher-** [comment]
Closed due to inactivity but please feel free to reopen this if you wish to pursue the issue.

**Comment by Thanoos** [comment]
make[3]: Entering directory '/home/awapal/awpcoin/src/univalue'
  CXX      lib/libunivalue_la-univalue.lo
  CXX      lib/libunivalue_la-univalue_read.lo
  CXX      lib/libunivalue_la-univalue_write.lo
  CXXLD    libunivalue.la
rm: cannot remove '.libs/libunivalue.a': Permission denied
rm: cannot remove '.libs/libunivalue.la': Permission denied
rm: cannot remove '.libs/libunivalue.lai': Permission denied
ar: `u' modifier ignored since `D' is the default (see `U')
ar: could not create temporary file whilst writing archive: No more archived files
Makefile:744: recipe for target 'libunivalue.la' failed
make[3]: *** [libunivalue.la] Error 1
make[3]: Leaving directory '/home/awapal/awpcoin/src/univalue'
Makefile:9848: recipe for target 'univalue/libunivalue.la' failed
make[2]: *** [univalue/libunivalue.la] Error 2
make[2]: Leaving directory '/home/awapal/awpcoin/src'
Makefile:9344: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/awapal/awpcoin/src'
Makefile:741: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 

can someone help me with this. I am trying to make a coin from awpcoin by forking liotecoin v 0.15.1
