### ISSUE TITLE
Can't build depends on Ubuntu 22 jammy

### ISSUE THREAD

**Issue by yodel-settles** [litecoin-project/litecoin#872]
Describe issue: Need to compile depends, ran make, errors out

Expected: Clean depends build

Actual: Tons of errors and warning messages

Reproduce? Every time

**Comment by abdulMohizQ** [comment]
use ubuntu 16.

**Comment by abdulMohizQ** [comment]
> Describe issue: Need to compile depends, ran make, errors out
> 
> Expected: Clean depends build
> 
> Actual: Tons of errors and warning messages
> 
> Reproduce? Every time

use ubuntu 16

**Comment by losh11** [comment]
Closing due to inability to replicate. Currently on a new Ubuntu 22.04 LTS machine and able to build without any issues following the `build-unix.md` document. Would appreciate more info in the future.

Don't have `libfmt`? make sure to `apt install libfmt-dev`.
Missing `db_cxx.h` header? make sure to install berkleydb, either the reccomended version, or you can also use 5.1 with incompatible bdb set during your configure.

**Comment by TheComputerGenie** [comment]
> make sure to install berkleydb

A depends build shouldn't have to; that's the entire point of having bdb in depends!
