### ISSUE TITLE
When LiteCoin Core Will Start Use SQLLite Like Bitcoin?

### ISSUE THREAD

**Issue by younicoin** [litecoin-project/litecoin#896]
Hello! As I noted, bitcoin master branch now doesn't have contrib/install_db4.sh, and I can build bitcoin on Devuan without installing BerkeleyDB version 4 from that script install_db4.sh (Devuan has BerkeleyDB 5 and has not version 4).
So, it is no longer necessary for me to install db4 and use its prefix in configure script. Bitcoin will use sqllite if bdb 4 absent:

```
./configure
  with wallet     = yes
    with sqlite   = yes
    with bdb      = no
```
This shows that bitcoin didn't found bdb4 and uses sqlite.

But I see Litecoin still has contrib/install_db4.sh, and tries to find BerkeleyDB version 4 if I just run ./configure

```
checking for lupdate... /usr/lib/x86_64-linux-gnu/qt5/bin/lupdate
checking whether to build Litecoin Core GUI... yes (Qt5)
checking for Berkeley DB C++ headers... no
configure: error: libdb_cxx headers missing, Litecoin Core requires this library for wallet functionality (--disable-wallet to disable wallet functionality)
```

Litecoin now requires BerkeleyDB 4 installed somewhere and defined in prefix like this:

```
export BDB_PREFIX='/usr/local/db4'
./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include"
```

I wish to know when this repository will start use sqlite also ? This is just a question for interest. Does LiteCoin update this repository and implement some new bitcoin's functionality and improvements?

**Comment by losh11** [comment]
The next release of Litecoin Core, v24, is currently under development.

Bitcoin Core is currently working on removing legacy wallets, and replacing them with descriptor wallets.
As descriptor wallets aren't backwards compatible, the decision was made to replace bdb with sqlite.
In Litecoin Core v0.21.2.x we haven't enabled descriptor wallets due to additional complexity from MWEB.
However I'd imagine this will change for the next release. David Burkett will have to confirm.

If this does change, that means we too will be removing bdb4 and replacing with sqlite.

> When LiteCoin Core Will Start Use BerkeleyDB 5?

Never. Switching to sqlite means no more need to use bdb. I believe Litecoin and Bitcoin Core have both used bdb4 for over a decade. bdb5 is not backwards compatible. To read more about why sqlite was used over bdb5 please read this: https://bitcoin.stackexchange.com/a/99621
